spring:
  application:
    name: companies-crud-prod
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: admin
    password: root
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
